spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: @MYSQL_PASSWORD@
        url: @MYSQL_URL@
        username: @MYSQL_USERNAME@
        #Poner credenciales base de datos local aca
        #password: ${MYSQL_PASSWORD}
        #url: ${MYSQL_URL}
        #username: ${MYSQL_USERNAME}
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false


    mail:
        host: smtp.gmail.com
        port: 587
        username: BookingGrupo7@gmail.com
        password: lwmzdelwzwwigyoi
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true