variables:
  DIR_ROOT: ${CI_PROJECT_DIR}/backend/HospedajeDH
  DIR: backend/HospedajeDH

before_script:
  - cd ${DIR_ROOT}
#coment
stages:
    - build
    - deploy

build-backend:
    stage: build
    image:  maven:3.8.1-openjdk-17-slim
    script:
        - echo "Building app..."
        #- mvn clean install
        - export
        - echo $MYSQL_URL
        - echo $MYSQL_USERNAME
        - echo $MYSQL_PASSWORD
        - mvn -DMYSQL_URL=$MYSQL_URL -DMYSQL_USERNAME=$MYSQL_USERNAME -DMYSQL_PASSWORD=$MYSQL_PASSWORD clean install -B -P no-tests
        - echo "Finished building the app."
    artifacts:
        expire_in: 1 week
        paths:
            - ${DIR_ROOT}/target/consoleapp.jar
    only:
      changes:
        - backend/HospedajeDH/**/*

deploy-backend:
    stage: deploy
    image: alpine:3.11
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp ${DIR_ROOT}/target/consoleapp.jar ubuntu@$DEPLOY_SERVER_IP:~/console-app/
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start consoleapp.service"
        - echo "Finished deploying the app."
    only:
      changes:
        - backend/HospedajeDH/**/*
    when: manual